import Head from "next/head";
import MovieList from "@/components/MovieList";
import { Heading } from "@chakra-ui/react";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading mt={10} mb={5} textAlign="center">Movie flix</Heading>
    <MovieList/>

    </>
  );
}
